In [4]:
import pandas as pd



df = pd.read_csv("llama3-inference-sat-math/the_inference_llama3_sat_math.csv")

In [5]:
df

,ID,Question,Output,Run_1
0,27493,"Below is an instruction that describes a task,...","Below is an instruction that describes a task,...",There were 711 people who got food.
1,5044,"Below is an instruction that describes a task,...","Below is an instruction that describes a task,...",The number we are looking for is 70.
2,24753,"Below is an instruction that describes a task,...","Below is an instruction that describes a task,...",Grapes average 3 seeds each.
3,22729,"Below is an instruction that describes a task,...","Below is an instruction that describes a task,...",The ratio of the number of hours Wolverine wor...
4,5162,"Below is an instruction that describes a task,...","Below is an instruction that describes a task,...",A = 1.
...,...,...,...,...
6285,24714,"Below is an instruction that describes a task,...","Below is an instruction that describes a task,...",Rocco has 110 piles of pennies.
6286,23444,"Below is an instruction that describes a task,...","Below is an instruction that describes a task,...",Jeffrey takes a total of 330 steps to go from ...
6287,24428,"Below is an instruction that describes a task,...","Below is an instruction that describes a task,...",Each token gets you 3.75 pitches.
6288,19104,"Below is an instruction that describes a task,...","Below is an instruction that describes a task,...",Kaylee sold 3 boxes of lemon biscuits to her a...
6289,241,"Below is an instruction that describes a task,...","Below is an instruction that describes a task,...",It will take 80 minutes for the candle to be 1...

In [8]:
from datasets import load_dataset, DatasetDict, Dataset

sat_math_dict = load_dataset("knazarali3/group2_processed_sat_math_cot")
test_dataset = sat_math_dict["test"]

test_dataset = sat_math_dict["test"]
    
test_dataset_df = pd.DataFrame(test_dataset)
test_dataset_df

,id,question,answer,is_correct,correct_reasoning_chain,index
0,27493,A few friends are making a small movie. They h...,There were 50 people there.,True,{'final_answer': 'There were 50 people there.'...,29793
1,5044,Subtracting 36 from a number and multipling by...,The number I'm looking for is 70.,True,{'final_answer': 'The number I'm looking for i...,7344
2,24753,Steven's teacher sends the class an assignment...,Grapes average 3 seeds each.,True,{'final_answer': 'Grapes average 3 seeds each....,27053
3,22729,"In a week, Rayman works out for half the numbe...",40/J,True,"{'final_answer': '40/J', 'steps': [{'explanati...",25029
4,5162,Find A from the 4-digit equation A2B2+1C1D=3333.,A = 2.,True,"{'final_answer': 'A = 2.', 'steps': [{'explana...",7462
...,...,...,...,...,...,...
6285,24714,Rocco stores his coins in piles of 10 coins ea...,Rocco has 5 piles of pennies.,True,{'final_answer': 'Rocco has 5 piles of pennies...,27014
6286,23444,"When Jeffrey walks, for every three steps forw...",Jeffrey takes 330 steps in total.,True,{'final_answer': 'Jeffrey takes 330 steps in t...,25744
6287,24428,Macy and Piper went to the batting cages. Each...,Each token gets you 15 pitches.,True,{'final_answer': 'Each token gets you 15 pitch...,26728
6288,19104,Kaylee needs to sell 33 boxes of biscuits. So ...,Kaylee sold 12 boxes of lemon biscuits to her ...,True,{'final_answer': 'Kaylee sold 12 boxes of lemo...,21404
6289,241,You have a candle that is 25 centimeters (cm) ...,It will take 80 minutes for the candle to be 1...,True,{'final_answer': 'It will take 80 minutes for ...,2541

In [10]:
llama3_test_dataset= df.merge(test_dataset_df, left_on='ID', right_on='id')

In [11]:
llama3_test_dataset

,ID,Question,Output,Run_1,id,question,answer,is_correct,correct_reasoning_chain,index
0,27493,"Below is an instruction that describes a task,...","Below is an instruction that describes a task,...",There were 711 people who got food.,27493,A few friends are making a small movie. They h...,There were 50 people there.,True,{'final_answer': 'There were 50 people there.'...,29793
1,5044,"Below is an instruction that describes a task,...","Below is an instruction that describes a task,...",The number we are looking for is 70.,5044,Subtracting 36 from a number and multipling by...,The number I'm looking for is 70.,True,{'final_answer': 'The number I'm looking for i...,7344
2,24753,"Below is an instruction that describes a task,...","Below is an instruction that describes a task,...",Grapes average 3 seeds each.,24753,Steven's teacher sends the class an assignment...,Grapes average 3 seeds each.,True,{'final_answer': 'Grapes average 3 seeds each....,27053
3,22729,"Below is an instruction that describes a task,...","Below is an instruction that describes a task,...",The ratio of the number of hours Wolverine wor...,22729,"In a week, Rayman works out for half the numbe...",40/J,True,"{'final_answer': '40/J', 'steps': [{'explanati...",25029
4,5162,"Below is an instruction that describes a task,...","Below is an instruction that describes a task,...",A = 1.,5162,Find A from the 4-digit equation A2B2+1C1D=3333.,A = 2.,True,"{'final_answer': 'A = 2.', 'steps': [{'explana...",7462
...,...,...,...,...,...,...,...,...,...,...
6285,24714,"Below is an instruction that describes a task,...","Below is an instruction that describes a task,...",Rocco has 110 piles of pennies.,24714,Rocco stores his coins in piles of 10 coins ea...,Rocco has 5 piles of pennies.,True,{'final_answer': 'Rocco has 5 piles of pennies...,27014
6286,23444,"Below is an instruction that describes a task,...","Below is an instruction that describes a task,...",Jeffrey takes a total of 330 steps to go from ...,23444,"When Jeffrey walks, for every three steps forw...",Jeffrey takes 330 steps in total.,True,{'final_answer': 'Jeffrey takes 330 steps in t...,25744
6287,24428,"Below is an instruction that describes a task,...","Below is an instruction that describes a task,...",Each token gets you 3.75 pitches.,24428,Macy and Piper went to the batting cages. Each...,Each token gets you 15 pitches.,True,{'final_answer': 'Each token gets you 15 pitch...,26728
6288,19104,"Below is an instruction that describes a task,...","Below is an instruction that describes a task,...",Kaylee sold 3 boxes of lemon biscuits to her a...,19104,Kaylee needs to sell 33 boxes of biscuits. So ...,Kaylee sold 12 boxes of lemon biscuits to her ...,True,{'final_answer': 'Kaylee sold 12 boxes of lemo...,21404
6289,241,"Below is an instruction that describes a task,...","Below is an instruction that describes a task,...",It will take 80 minutes for the candle to be 1...,241,You have a candle that is 25 centimeters (cm) ...,It will take 80 minutes for the candle to be 1...,True,{'final_answer': 'It will take 80 minutes for ...,2541

In [23]:
import re
def extract_numbers(s):
    # Normalize the string by removing unwanted characters, e.g., superscripts or similar
    normalized = re.sub(r'[^\d\s]', '', s)  # Keep only digits and spaces
    return list(map(int, re.findall(r'\d+', normalized)))  # Extract and convert to integers


def compare_number_lists(list1, list2):
    return set(list1) == set(list2)  # Use sets to ignore order

# Extract numbers from each column
llama3_test_dataset['solution_number'] = llama3_test_dataset['answer'].apply(extract_numbers)
llama3_test_dataset['model_solution_number'] = llama3_test_dataset['Run_1'].apply(extract_numbers)

# Compare the extracted numbers
llama3_test_dataset['llama3_is_correct'] = [
    compare_number_lists(a, b) for a, b in zip(llama3_test_dataset['solution_number'], llama3_test_dataset['model_solution_number'])
]
llama3_test_dataset

,ID,Question,Output,Run_1,id,question,answer,is_correct,correct_reasoning_chain,index,solution_number,model_solution_number,llama3_is_correct
0,27493,"Below is an instruction that describes a task,...","Below is an instruction that describes a task,...",There were 711 people who got food.,27493,A few friends are making a small movie. They h...,There were 50 people there.,True,{'final_answer': 'There were 50 people there.'...,29793,[50],[711],False
1,5044,"Below is an instruction that describes a task,...","Below is an instruction that describes a task,...",The number we are looking for is 70.,5044,Subtracting 36 from a number and multipling by...,The number I'm looking for is 70.,True,{'final_answer': 'The number I'm looking for i...,7344,[70],[70],True
2,24753,"Below is an instruction that describes a task,...","Below is an instruction that describes a task,...",Grapes average 3 seeds each.,24753,Steven's teacher sends the class an assignment...,Grapes average 3 seeds each.,True,{'final_answer': 'Grapes average 3 seeds each....,27053,[3],[3],True
3,22729,"Below is an instruction that describes a task,...","Below is an instruction that describes a task,...",The ratio of the number of hours Wolverine wor...,22729,"In a week, Rayman works out for half the numbe...",40/J,True,"{'final_answer': '40/J', 'steps': [{'explanati...",25029,[40],[11],False
4,5162,"Below is an instruction that describes a task,...","Below is an instruction that describes a task,...",A = 1.,5162,Find A from the 4-digit equation A2B2+1C1D=3333.,A = 2.,True,"{'final_answer': 'A = 2.', 'steps': [{'explana...",7462,[2],[1],False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6285,24714,"Below is an instruction that describes a task,...","Below is an instruction that describes a task,...",Rocco has 110 piles of pennies.,24714,Rocco stores his coins in piles of 10 coins ea...,Rocco has 5 piles of pennies.,True,{'final_answer': 'Rocco has 5 piles of pennies...,27014,[5],[110],False
6286,23444,"Below is an instruction that describes a task,...","Below is an instruction that describes a task,...",Jeffrey takes a total of 330 steps to go from ...,23444,"When Jeffrey walks, for every three steps forw...",Jeffrey takes 330 steps in total.,True,{'final_answer': 'Jeffrey takes 330 steps in t...,25744,[330],[330],True
6287,24428,"Below is an instruction that describes a task,...","Below is an instruction that describes a task,...",Each token gets you 3.75 pitches.,24428,Macy and Piper went to the batting cages. Each...,Each token gets you 15 pitches.,True,{'final_answer': 'Each token gets you 15 pitch...,26728,[15],[375],False
6288,19104,"Below is an instruction that describes a task,...","Below is an instruction that describes a task,...",Kaylee sold 3 boxes of lemon biscuits to her a...,19104,Kaylee needs to sell 33 boxes of biscuits. So ...,Kaylee sold 12 boxes of lemon biscuits to her ...,True,{'final_answer': 'Kaylee sold 12 boxes of lemo...,21404,[12],[3],False
6289,241,"Below is an instruction that describes a task,...","Below is an instruction that describes a task,...",It will take 80 minutes for the candle to be 1...,241,You have a candle that is 25 centimeters (cm) ...,It will take 80 minutes for the candle to be 1...,True,{'final_answer': 'It will take 80 minutes for ...,2541,"[80, 11]","[80, 11]",True

In [24]:
llama3_test_dataset["llama3_is_correct"].value_counts()

llama3_is_correct
True     3700
False    2590
Name: count, dtype: int64